version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
  db:
    image: postgres:14-alpine
    container_name: postgres_employee_server
    ports:
      - "5432:5432"
    env_file:
      - .env